services:
  # Backend API Service
  - type: web
    name: studybuddy-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: BACKEND_CORS_ORIGINS
        value: https://studybuddy-frontend.onrender.com,http://localhost:5173
      - key: OPENAI_MODEL
        value: gpt-4-turbo-preview
      - key: OPENAI_MAX_TOKENS
        value: 4000
      - key: OPENAI_TEMPERATURE
        value: 0.7
    healthCheckPath: /health

  # Frontend Service
  - type: web
    name: studybuddy-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://studybuddy-backend.onrender.com

